<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<RepositoryUrl>https://github.com/rebus-org/Freakout</RepositoryUrl>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<IncludeSymbols>True</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
		<PackageIcon>transparent_2024-04-11T18-52-17_cropped.png</PackageIcon>
		<GenerateDocumentationFile>True</GenerateDocumentationFile>
	</PropertyGroup>

	<ItemGroup>
		<None Include="..\artwork\transparent_2024-04-11T18-52-17_cropped.png">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
		<None Include="..\README.md">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Freakout\Freakout.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="sequentialguid" Version="6.1.0" />
		<PackageReference Include="marten" Version="8.37.0" />
	</ItemGroup>

</Project>
