<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\Freakout.NpgSql\Freakout.NpgSql.csproj" />
		<ProjectReference Include="..\Freakout.Tests\Freakout.Tests.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="microsoft.extensions.dependencyinjection" Version="10.0.11" />
		<PackageReference Include="microsoft.extensions.hosting" Version="10.0.11" />
		<PackageReference Include="microsoft.extensions.logging" Version="10.0.11" />
		<PackageReference Include="microsoft.net.test.sdk" Version="18.9.0" />
		<PackageReference Include="nunit3testadapter" Version="6.2.0" />
		<PackageReference Include="Testcontainers.PostgreSql" Version="4.14.0" />
	</ItemGroup>

</Project>
