<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\Freakout.Testing\Freakout.Testing.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="microsoft.net.test.sdk" Version="18.5.1" />
		<PackageReference Include="nunit" Version="4.6.0" />
		<PackageReference Include="testy" Version="0.10.0" />
		<PackageReference Include="microsoft.extensions.dependencyinjection" Version="10.0.8" />
	</ItemGroup>

</Project>
